# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backendcore.sync.proto.coupon_pb2 as coupon__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import backendcore.sync.proto.vendor_pb2 as vendor__pb2


class RemoteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCoupon = channel.unary_unary(
                '/remote.RemoteService/CreateCoupon',
                request_serializer=coupon__pb2.Coupon.SerializeToString,
                response_deserializer=coupon__pb2.Coupon.FromString,
                )
        self.CreateVendor = channel.unary_unary(
                '/remote.RemoteService/CreateVendor',
                request_serializer=vendor__pb2.Vendor.SerializeToString,
                response_deserializer=vendor__pb2.Vendor.FromString,
                )
        self.DestroyCoupon = channel.unary_unary(
                '/remote.RemoteService/DestroyCoupon',
                request_serializer=coupon__pb2.Coupon.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.DestroyVendor = channel.unary_unary(
                '/remote.RemoteService/DestroyVendor',
                request_serializer=vendor__pb2.Vendor.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class RemoteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVendor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyVendor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCoupon,
                    request_deserializer=coupon__pb2.Coupon.FromString,
                    response_serializer=coupon__pb2.Coupon.SerializeToString,
            ),
            'CreateVendor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVendor,
                    request_deserializer=vendor__pb2.Vendor.FromString,
                    response_serializer=vendor__pb2.Vendor.SerializeToString,
            ),
            'DestroyCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyCoupon,
                    request_deserializer=coupon__pb2.Coupon.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DestroyVendor': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyVendor,
                    request_deserializer=vendor__pb2.Vendor.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote.RemoteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote.RemoteService/CreateCoupon',
            coupon__pb2.Coupon.SerializeToString,
            coupon__pb2.Coupon.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateVendor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote.RemoteService/CreateVendor',
            vendor__pb2.Vendor.SerializeToString,
            vendor__pb2.Vendor.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote.RemoteService/DestroyCoupon',
            coupon__pb2.Coupon.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyVendor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote.RemoteService/DestroyVendor',
            vendor__pb2.Vendor.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
